name: material_icons
description: Google Material icons - optimized for Dart + SASS
version: 0.0.1

author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-icons

#dependencies:
#  lib_name: any
#dev_dependencies:
#  unittest: any
