name: material_icons_purple_sample
version: 0.0.1
description: A purble sample for material_icons
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  material_icons:
    path: ../../
